---
name: gui
event_server:
    eventer_server:
        host: 127.0.0.1
        port: 23012
address:
    host: 0.0.0.0
    port: 23023
adapters:
    - module: scada.adapter
      name: adapter
views:
    - name: login
      builtin: login
      conf: null
    - name: grid
      view_path: ./view/grid
      conf: null
initial_view: login
users:
    - name: user
      password:
          hash: cef3cf37b4fa2a692f06d6e637e112bd3a37179a8c6752c115ff21813a816574
          salt: 497b53087260002cd62ffabc94267437
      roles:
          - user_role
      view: grid
log:
    disable_existing_loggers: false
    formatters:
        default: {}
    handlers:
        syslog:
            class: hat.syslog.handler.SysLogHandler
            comm_type: TCP
            formatter: default
            host: 127.0.0.1
            level: INFO
            port: 6514
            queue_size: 10
    root:
        handlers:
        - syslog
        level: INFO
    version: 1
...
