---
name: gui
event_server:
    eventer_server:
        host: 127.0.0.1
        port: 23012
address:
    host: 0.0.0.0
    port: 23023
adapters:
  - module: air_supervision.adapters.timeseries
    name: timeseries
views:
  - name: login
    builtin: login
    conf: null
  - name: main
    view_path: build/views/main
    conf: null
initial_view: login
users:
  - name: user1
    password:
        hash: 0927f26c1e200037ef44e622d39d5b7c201690c85b9aa86545d6583ecff2b02f
        salt: 7af08c40f25d800fa3d1ab3f8199adbd
    roles:
        - user
    view: main
log:
  disable_existing_loggers: false
  formatters:
    default: {}
  handlers:
    syslog:
      class: hat.syslog.handler.SysLogHandler
      host: 127.0.0.1
      port: 6514
      comm_type: TCP
      level: INFO
      formatter: default
      queue_size: 50
  root:
    handlers:
      - syslog
    level: INFO
  version: 1
...
